### PR TITLE
add projects field in group content type

### PR DESCRIPTION
**Pull request by danielmarlon**

### CODE REVIEW

**Comment by revagomes** [comment]
@danielmarlon Esse PR está configurado erroneamente para o base branch `master`. Favor atualizar o base branch ou criar um novo PR para adicionar suas modificações no branch `pece2.0`.

**Comment by revagomes** [comment]
@danielmarlon Any news on this PR? 
Is there any feature not covered by you newer PR? Can I closed it?

**Comment by danielmarlon** [comment]
I’m not in laboratory with the computer with the project, I will am in the Monday, sorry for answer your email so late.

Enviado do Email para Windows 10

De: Renato Vasconcellos Gomes
Enviado:sexta-feira, 13 de setembro de 2019 15:09
Para: PECE-project/drupal-pece
Cc:Daniel Marlon; Mention
Assunto: Re: [PECE-project/drupal-pece] add projects field in group contenttype (#89)

@danielmarlon Any news on this PR?
Is there any feature not covered by you newer PR? Can I closed it?

**Comment by edmargomes** [comment]
Pull request aberto para o branch errado

**Comment by edmargomes** [comment]
#89

**Pull request closed without merging**
